package net.ximatai.muyun.spring.platform.workflow;

import java.time.Instant;
import java.util.List;

public record WorkflowWorkbenchCard(
        String boardType,
        String instanceId,
        String moduleAlias,
        String recordId,
        String definitionId,
        String workflowVersionId,
        WorkflowInstanceStatus instanceStatus,
        WorkflowApprovalStatus approvalStatus,
        String taskId,
        WorkflowTaskKind taskKind,
        WorkflowTaskStatus taskStatus,
        String nodeKey,
        String nodeTitle,
        String currentNodeKeys,
        List<String> currentAssigneeIds,
        List<String> currentAssigneeTitles,
        Instant startedAt,
        Instant receivedAt,
        Instant completedAt,
        String actionCode,
        WorkflowOvertimeStatus overtimeStatus,
        Instant dueAt,
        Instant lastOperatedAt,
        WorkflowAssignmentKind assignmentKind,
        String originalAssigneeId,
        String originalAssigneeTitle,
        String delegatedFromUserId,
        String delegatedFromUserTitle,
        String delegatedToUserId,
        String delegatedToUserTitle,
        Boolean principalCanProcess,
        WorkflowNoticeReadStatus readStatus,
        String noticeSourceType,
        Integer delegationTaskCount,
        Boolean addedByAddSign,
        String addSignSourceNodeKey,
        String addSignOperatorId,
        String addSignOperatorTitle,
        Instant addSignAt,
        String submitterUserId,
        String submitterUserTitle,
        WorkflowRecordSummary business
) {

    public WorkflowWorkbenchCard(String boardType,
        String instanceId,
        String moduleAlias,
        String recordId,
        String definitionId,
        String workflowVersionId,
        WorkflowInstanceStatus instanceStatus,
        WorkflowApprovalStatus approvalStatus,
        String taskId,
        WorkflowTaskKind taskKind,
        WorkflowTaskStatus taskStatus,
        String nodeKey,
        String nodeTitle,
        String currentNodeKeys,
        List<String> currentAssigneeIds,
        List<String> currentAssigneeTitles,
        Instant startedAt,
        Instant receivedAt,
        Instant completedAt,
        String actionCode,
        WorkflowOvertimeStatus overtimeStatus,
        Instant dueAt,
        Instant lastOperatedAt,
        WorkflowAssignmentKind assignmentKind,
        String originalAssigneeId,
        String originalAssigneeTitle,
        String delegatedFromUserId,
        String delegatedFromUserTitle,
        String delegatedToUserId,
        String delegatedToUserTitle,
        Boolean principalCanProcess,
        WorkflowNoticeReadStatus readStatus,
        String noticeSourceType,
        Integer delegationTaskCount,
        Boolean addedByAddSign,
        String addSignSourceNodeKey,
        String addSignOperatorId,
        String addSignOperatorTitle,
        Instant addSignAt,
        String submitterUserId,
        String submitterUserTitle) {
        this(boardType, instanceId, moduleAlias, recordId, definitionId, workflowVersionId, instanceStatus, approvalStatus, taskId, taskKind, taskStatus, nodeKey, nodeTitle, currentNodeKeys, currentAssigneeIds, currentAssigneeTitles, startedAt, receivedAt, completedAt, actionCode, overtimeStatus, dueAt, lastOperatedAt, assignmentKind, originalAssigneeId, originalAssigneeTitle, delegatedFromUserId, delegatedFromUserTitle, delegatedToUserId, delegatedToUserTitle, principalCanProcess, readStatus, noticeSourceType, delegationTaskCount, addedByAddSign, addSignSourceNodeKey, addSignOperatorId, addSignOperatorTitle, addSignAt, submitterUserId, submitterUserTitle, null);
    }

    public WorkflowWorkbenchCard withBusiness(WorkflowRecordSummary summary) {
        return new WorkflowWorkbenchCard(boardType, instanceId, moduleAlias, recordId, definitionId, workflowVersionId, instanceStatus, approvalStatus, taskId, taskKind, taskStatus, nodeKey, nodeTitle, currentNodeKeys, currentAssigneeIds, currentAssigneeTitles, startedAt, receivedAt, completedAt, actionCode, overtimeStatus, dueAt, lastOperatedAt, assignmentKind, originalAssigneeId, originalAssigneeTitle, delegatedFromUserId, delegatedFromUserTitle, delegatedToUserId, delegatedToUserTitle, principalCanProcess, readStatus, noticeSourceType, delegationTaskCount, addedByAddSign, addSignSourceNodeKey, addSignOperatorId, addSignOperatorTitle, addSignAt, submitterUserId, submitterUserTitle, summary);
    }

    public WorkflowWorkbenchCard {
        currentAssigneeIds = currentAssigneeIds == null ? List.of() : List.copyOf(currentAssigneeIds);
        currentAssigneeTitles = currentAssigneeTitles == null ? List.of() : List.copyOf(currentAssigneeTitles);
        addedByAddSign = Boolean.TRUE.equals(addedByAddSign);
    }

    public WorkflowWorkbenchCard(String boardType,
                                 String instanceId,
                                 String moduleAlias,
                                 String recordId,
                                 String definitionId,
                                 String workflowVersionId,
                                 WorkflowInstanceStatus instanceStatus,
                                 WorkflowApprovalStatus approvalStatus,
                                 String taskId,
                                 WorkflowTaskKind taskKind,
                                 WorkflowTaskStatus taskStatus,
                                 String nodeKey,
                                 String nodeTitle,
                                 String currentNodeKeys,
                                 List<String> currentAssigneeIds,
                                 List<String> currentAssigneeTitles,
                                 Instant startedAt,
                                 Instant receivedAt,
                                 Instant completedAt,
                                 String actionCode,
                                 WorkflowOvertimeStatus overtimeStatus,
                                 Instant dueAt,
                                 Instant lastOperatedAt,
                                 WorkflowAssignmentKind assignmentKind,
                                 String originalAssigneeId,
                                 String originalAssigneeTitle,
                                 String delegatedFromUserId,
                                 String delegatedFromUserTitle,
                                 String delegatedToUserId,
                                 String delegatedToUserTitle,
                                 Boolean principalCanProcess,
                                 WorkflowNoticeReadStatus readStatus,
                                 String noticeSourceType,
                                 Integer delegationTaskCount,
                                 Boolean addedByAddSign,
                                 String addSignSourceNodeKey,
                                 String addSignOperatorId,
                                 String addSignOperatorTitle,
                                 Instant addSignAt) {
        this(boardType, instanceId, moduleAlias, recordId, definitionId, workflowVersionId, instanceStatus,
                approvalStatus, taskId, taskKind, taskStatus, nodeKey, nodeTitle, currentNodeKeys,
                currentAssigneeIds, currentAssigneeTitles, startedAt, receivedAt, completedAt, actionCode,
                overtimeStatus, dueAt, lastOperatedAt, assignmentKind, originalAssigneeId, originalAssigneeTitle,
                delegatedFromUserId, delegatedFromUserTitle, delegatedToUserId, delegatedToUserTitle,
                principalCanProcess, readStatus, noticeSourceType, delegationTaskCount, addedByAddSign,
                addSignSourceNodeKey, addSignOperatorId, addSignOperatorTitle, addSignAt, null, null);
    }

    public WorkflowWorkbenchCard(String boardType,
                                 String instanceId,
                                 String moduleAlias,
                                 String recordId,
                                 String definitionId,
                                 String workflowVersionId,
                                 WorkflowInstanceStatus instanceStatus,
                                 WorkflowApprovalStatus approvalStatus,
                                 String taskId,
                                 WorkflowTaskKind taskKind,
                                 WorkflowTaskStatus taskStatus,
                                 String nodeKey,
                                 String currentNodeKeys,
                                 List<String> currentAssigneeIds,
                                 Instant startedAt,
                                 Instant receivedAt,
                                 Instant completedAt,
                                 String actionCode,
                                 WorkflowOvertimeStatus overtimeStatus,
                                 Instant dueAt,
                                 Instant lastOperatedAt,
                                 WorkflowAssignmentKind assignmentKind,
                                 String originalAssigneeId,
                                 String delegatedFromUserId,
                                 String delegatedToUserId,
                                 Boolean principalCanProcess,
                                 String noticeSourceType,
                                 Integer delegationTaskCount) {
        this(boardType, instanceId, moduleAlias, recordId, definitionId, workflowVersionId, instanceStatus,
                approvalStatus, taskId, taskKind, taskStatus, nodeKey, nodeKey, currentNodeKeys, currentAssigneeIds,
                List.of(),
                startedAt, receivedAt, completedAt, actionCode, overtimeStatus, dueAt, lastOperatedAt,
                assignmentKind, originalAssigneeId, null, delegatedFromUserId, null, delegatedToUserId, null,
                principalCanProcess, null, noticeSourceType, delegationTaskCount, false, null, null, null, null,
                null, null);
    }
}
